name: 1-Java Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      build_image:
        description: 'Docker image for the build'
        required: true
        default: 'openjdk:11-jdk'

env:
  BUILD_IMAGE: ${{ github.event.inputs.build_image || 'openjdk:11-jdk' }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: ${{ env.BUILD_IMAGE }}
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Package application
      uses: ./.github/workflows/common-build.yml
