name: 2-Packaging

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Name of the release'
        required: true
        default: 'Release v1.0.0'

permissions:
  contents: read
  pull-requests: write

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.set_release_name.outputs.release_name }}
    steps:
      - name: Set var for release name
        id: set_release_name
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Setting release name"
          echo `RELEASE_NAME="Release ${{ github.ref }}"` >> $GITHUB_ENV

  call-packaging:
    needs: preparation
    uses: ./.github/workflows/2-reusable-packaging.yml
    with:
      tag_name: ${{ github.event.inputs.tag_name || github.ref }}
      release_name: ${{ github.event.inputs.release_name ||  needs.preparation.outputs.release_name }}
