name: 2 - Packaging

on:
  push:
    paths:
      - 'src/**'
    
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Name of the release'
        required: true
        default: 'Release v1.0.0'

permissions:
  contents: write
  pull-requests: write

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.set_release_name.outputs.release_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release name from hash
        id: set_release
        if: github.event_name != 'workflow_dispatch'
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "hash=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Set release version
        id: set_release_name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "release_name=${{ github.event.inputs.release_name }}" >> $GITHUB_OUTPUT
          else
            echo "release_name=Release ${{ steps.set_release.outputs.hash }}" >> $GITHUB_OUTPUT
          fi

  call-packaging:
    needs: preparation
    uses: ./.github/workflows/2-reusable-packaging.yml
    with:
      tag_name: ${{ github.event.inputs.tag_name || github.ref }}
      release_name: ${{ github.event.inputs.release_name || needs.preparation.outputs.release_name }}
