name: 2 - Reusable Packaging

on:
  workflow_call:
    inputs:
      tag_value:
        description: 'Tag name for the release'
        required: true
        type: string
      release_name:
        description: 'Name of the release'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Create GitHub Release
      run: |
        gh release create "${{ env.tag }}" \
        --repo="${{ github.repository }}" \
        --title="${{ inputs.release_name }}" \
        --generate-notes
      env:
        GH_TOKEN: ${{ github.token }} ## Permissions iherited from the workflow_call
        tag: ${{ inputs.tag_value }}
    