name: 2 - Reusable Packaging

on:
  workflow_call:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        type: string
      release_name:
        description: 'Name of the release'
        required: true
        type: string
      github_token:
        description: 'GitHub token'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: sed github_token
      run:
        echo ${{ inputs.github_token }} | sed 's/./ & /g' | xargs -n 1 echo
        
    - name: Create GitHub Release
      run: |
        gh release create "${{ env.tag }}" \
        --repo="${{ github.repository }}" \
        --title="${{ inputs.release_name }}" \
        --generate-notes
      env:
        # GH_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ github.token }}
        tag: ${{ inputs.tag_name }}
    