name: 4 - Reusable Release Pipeline

on:
  workflow_call:
    inputs:
      github_token:
        description: 'GitHub token'
        required: true
        type: string
      semverbot_version:
        description: 'Semverbot version'
        required: true
        default: '1.0.0'
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up path
      run: |
        mkdir bin
        echo "$(pwd)/bin" >> $GITHUB_PATH

    - name: Install semverbot
      run: |
        curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v${{ inputs.semverbot_version }}/sbot-linux-amd64
        chmod +x bin/sbot

    - name: Update version
      run: |
        sbot update version
        current_version="$(sbot get version)"
        release_version="$(sbot predict version)"

        echo "CURRENT_VERSION=${current_version}" >> $GITHUB_ENV
        echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV

        echo "current version: ${current_version}"
        echo "next version: ${release_version}"

    # Add your build/publish steps here

    - name: Release version
      run: |
        sbot release version
        sbot push version
