name: 5 - Release Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry'
        required: true
        default: 'ghcr.io'
      image_version:
        description: 'Image version'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  preparation:
    outputs:
      image_version: ${{ github.event.inputs.image_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Image version for workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo set-output name=image_version::${{ github.event.inputs.image_version }}

      - name: Image version from hash
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo set-output name=image_version::${{ github.sha }}

  publish-image:
    needs: preparation
    uses: ./.github/workflows/5-reusable-publish-docker.yml
    with:
      registry: 'ghcr.io'
      image_name: ${{ github.repository }}
      image_version: ${{ needs.preparation.outputs.image_version }}
    secrets:
      github_token: ${{ github.token }}
