name: 5 - Release Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry'
        required: true
        default: 'ghcr.io'
      image_version:
        description: 'Image version'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  preparation:
    outputs:
      image_version:
      image_version: ${{ steps.set_image_version.outputs.image_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Image version from hash
        id: hash_step
        if: github.event_name != 'workflow_dispatch'
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "image_version=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Set image version
        id: set_image_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "image_version=${{ github.event.inputs.image_version }}" >> $GITHUB_OUTPUT
          else
            echo "image_version=${{ steps.hash_step.outputs.image_version }}" >> $GITHUB_OUTPUT

  publish-image:
    needs: preparation
    uses: ./.github/workflows/5-reusable-publish-docker.yml
    with:
      registry: 'ghcr.io'
      image_name: ${{ github.repository }}
      image_version: ${{ needs.preparation.outputs.image_version }}
    secrets:
      registry_pwd: ${{ SECRETS.GITHUB_TOKEN }}
