name: 5 - Reusable create and publish a Docker image

on:
  workflow_call:
    inputs:
      registry:
        description: 'Docker registry'
        required: true
        default: 'docker.io'
        type: string
      image_name:
        description: 'Docker image name'
        required: true
        default: ${{ github.repository }}
        type: string
      docker_username:
        description: 'Docker username'
        required: true
        type: string
      docker_password:
        description: 'Docker password'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}

      - name: Extract meta (tags, labels) for Docker
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ inputs.registry }}/${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ github.sha }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.docker_username }}/${{ inputs.image_name }}:latest
