name: 5 - Release Docker Image

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry'
        required: true
        default: 'docker.io'
      image_name:
        description: 'Docker image name'
        required: true
        default: ${{ github.repository }}
      docker_username:
        description: 'Docker username'
        required: true
      docker_password:
        description: 'Docker password'
        required: true

jobs:
  call-reusable-publish-docker:
    uses: ./.github/workflows/4-reusable-publish-docker.yml
    with:
      registry: ${{ github.event.inputs.registry }}
      image_name: ${{ github.event.inputs.image_name }}
      docker_username: ${{ github.event.inputs.docker_username }}
      docker_password: ${{ github.event.inputs.docker_password }}
